---
  - name: "Creates backend app directory"
    become: true
    file:
      path: ~/backend-dir
      state: directory
      
  - name: "Unarchive backend files"
    become: true
    unarchive:
      src: artifact.tar.gz
      dest: ~/backend-dir
      
  - name: "Installing Node Dependencies"
    shell: |
      cd ~/backend-dir
      npm i
      
  - name: "Executing Node app with PM2"
    shell: |
      cd ~/backend-dir/dist
      pm2 stop default
      pm2 start main.js
    register: execute_node

  - name: print message
    debug:
      msg: "{{ execute_node.stdout_lines }}"
      
  - name: "Configure pm2 to start as service"
    shell: |
      sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
      pm2 save